### ISSUE TITLE
Fatal Error / type hint error

### ISSUE THREAD

**Issue by 3lm4r** [andanteproject/period-bundle#1]
Hi there,

I'm getting the following error with the relesed version 1.1.2 and Symfony 4.4

Fatal error: Declaration of Andante\PeriodBundle\Form\DataMapper\PeriodDataMapper::mapDataToForms($viewData, iterable $forms): void must be compatible with Symfony\Component\Form\DataMapperInterface::mapDataToForms($viewData, $forms) in /..../vendor/andanteproject/period-bundle/src/Form/DataMapper/PeriodDataMapper.php on line 63

The type hint 'iterable' seems to be wrong.

**Comment by cristoforocervino** [comment]
Hi @3lm4r! Thanks for reporting the issue!
Try to update the library to v1.1.3 and let me know if everything works fine to you! 👍🏻

**Comment by 3lm4r** [comment]
It works like a charm! Thank you very much for the fast fix!
